### PR TITLE
Oracle moved Generated

### PR DESCRIPTION
**Pull request by dstuebe**
Oracle moved `Generated` in Java 9+
Problem is - it is not backward compatible for Java 7/8

Is this something you are already handling for other platforms or is Java the only language that is foolish enough to make these kinds of breaking changes?

### CODE REVIEW

**Comment by pascaldekloe** [comment]
Whow, now Oracle kills the endless compatibility pilar from Sun too? :open_mouth: Not even an migration path!?

Java is the only language with annotations for such things for as far as I know. More specifically, I think we should drop this annotation entirely and add an extra comment line (like the other languages already have) to describe the origin as in `The compiler used schema file x for package z.`. Do you agree?

**Comment by dstuebe** [comment]
Let's kill it - there is no way to justify the complexity it would
introduce to support multiple versions of java.

How can I help close the loop on this issue?

Best

David

**Comment by pascaldekloe** [comment]
Now I see the `javaPackage` template (in ./java.go) already has such comment line right after `Code generated by colf(1); DO NOT EDIT.`. We could do the same in the `javaCode` template, only with `{{.Pkg.SchemaFileList}}`.

I like to include the generated code (in ./java/gen) too because in that way commits are explicit on what the change did/is. Run make(1) in ./java for a refresh.

**Comment by pascaldekloe** [comment]
Shall I pick this one up?

**Comment by pascaldekloe** [comment]
Thanks for reporting this one David.

**Comment by dstuebe** [comment]
Thanks for picking it up. I am out of the office this week.

**Pull request closed without merging**
