### PR TITLE
Add superclass to generated Java classes

### PR DESCRIPTION
**Pull request by kbarrette**
Adds a common interface to the generated Java - I'd like to write code that interacts with any Colfer object, and this makes it quite a bit simpler.

I'm not much of a go programmer, so please let me know if something needs correction.

### CODE REVIEW

**Comment by pascaldekloe** [comment]
The Go code looks fine. This does create one interface per package though so not one for all.

For me to understand, can you give a usecase how this functionality is applied?

**Comment by kbarrette** [comment]
@pascaldekloe yeah, I couldn't figure out which package the interface would go in, so I made one per package. I'm open to suggestions about a better way!

My use case looks something like this:
```java
public class SerDe<T extends ColferObject> {
    byte[] serialize(T colfer) { }
    T deserialize(byte[] bytes) { }
}
```

**Comment by pascaldekloe** [comment]
We can make the interface generation an optional compiler flag and have the qualified name as an argument as in `colf -i com/example/Colferable java`.

Stil, what does that interface do? It delegates the actual codec execution to something anonymous like `Runable` does? Do you want to mock the serial or what is the purpose?

**Comment by kbarrette** [comment]
@pascaldekloe a compiler flag sounds OK to me.

I'm using a data store that requires me to pass serializer and deserializer functions to it. The `SerDe` class above lets me create one instance per Colfer type and pass the `serialize` and `deserialize` methods to my data store, rather than creating one method per type.

**Comment by pascaldekloe** [comment]
I see. That sounds like proper Java thinking.

Since this is quite specific, and there will be others for sure, how about not generating the interface at all? Instead we can just mark the beans to implement **any** provided interface(s). Users then can define their own abstractions and even add common methods.

**Comment by kbarrette** [comment]
@pascaldekloe I think allowing any interface creates the possibility that someone would provide an interface that the generated classes don't implement all the methods for, thereby rendering the generated Java code non-compilable.

How about providing a superclass rather than an interface?

**Comment by pascaldekloe** [comment]
Sure, why not a super class. I don't have a clear understanding of the pros and cons in that area.

Either way, it becomes possible to generate non-compiling code indeed. Freedom has its price.

**Comment by kbarrette** [comment]
Good point! A super class would allow implementation, where an interface only allows specification of a contract. Your choice as to which you'd prefer.

**Comment by pascaldekloe** [comment]
I'll stick with your judgement. Do you feel like making this change? If not I'll do it later. Definitely nice to have.

**Comment by kbarrette** [comment]
I'm happy to do it.

**Comment by kbarrette** [comment]
@pascaldekloe updated with superclass

**Comment by kbarrette** [comment]
@pascaldekloe thanks for accepting it! Any idea when you'll release a new pre-built binary? I need to make sure everyone working on this project is using this code.

**Comment by pascaldekloe** [comment]
The C port's not done yet. Needs another week or 3. Is that soon enough?

**Comment by kbarrette** [comment]
That'll be fine!

**Comment by pascaldekloe** [comment]
Release :white_check_mark: @kbarrette.

**Pull request merged**
