### PR TITLE
Assign binary list after deserializing it

### PR DESCRIPTION
**Pull request by kbarrette**
@pascaldekloe Looks like lists of binaries were not being actually assigned to the correct class member.

### CODE REVIEW

**Comment by pascaldekloe** [comment]
Jikes! How did this pass the unit tests in `./java/test.java`? The CI fail is just a coincident. I'm working on it right now...

**Comment by kbarrette** [comment]
I haven't deciphered `test.java`, but this should certainly fail a test.

**Comment by pascaldekloe** [comment]
It's because `#_equals(byte[],byte[])` is broken too. Fail! :face_with_thermometer: 
Do you feel like fixing it @kbarrette? Otherwise I will do so tonight.

**Comment by kbarrette** [comment]
Go for it! I won't have time this evening.

**Pull request merged**
