### PR TITLE
Java CodeGen Enhancements

### PR DESCRIPTION
**Pull request by guilt**
- Enable Interfaces.
- Enable Code Injection.

This was done in order to be able to use different interfaces in Java, albeit Serializable, with some
additional properties as well, such as being able to add unimplemented methods etc. for bookkeeping.

### CODE REVIEW

**Comment by pascaldekloe** [comment]
Thank you Karthik. 😃The functionality makes sense.  I'll do some minor modifications a bit later. Each of which will tag this issue so you can see the change.

**Comment by pascaldekloe** [comment]
Please let me know if you need a release...

**Comment by guilt** [comment]
I'm working on a Python generator :) If I complete it fairly quickly, would like a release with preliminary Python support

**Comment by pascaldekloe** [comment]
Really? 🤩 Whoah, super cool. I'm super excited about such possibility. Happy to help with the templates too.

**Pull request merged**
